---
title: "figures"
author: "Catherine DiGennaro"
date: "5/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(scales)
```


```{r}
plot_data <-
  grant_summary %>% #grant_summary is output by 'analyze ODs.rmd'
  pivot_longer(-year) %>%
  group_by(name) %>%
  summarize(growth = value[year == 2019] - value[year == 2011],
            pct_change = ((value[year == 2019]-value[year == 2011])/value[year == 2011])) %>%
  ungroup()

plot_data$name <-
  gsub("and synthetics with", "and synthetics\n with", plot_data$name)
plot_data$name <-
  gsub("cocaine with", "cocaine\n with", plot_data$name)
plot_data$name <-
  gsub("heroin and/or", "heroin\n and/or", plot_data$name)

order <-c(
  "Psychostimulants and synthetics\n with or without other opioids",
  "Cocaine and synthetics\n with or without other opioids",
  "Psychostimulants and cocaine\n with or without opioids",
  "Synthetics with or without other opioids",
  "Psychostimulants only",
  "Psychostimulants with heroin\n and/or Rx opioids",
  "Cocaine only",
  "Heroin with or without Rx opioids",
  "Cocaine with heroin\n and/or Rx opioids",
  "Rx opioids only"
) 
```

```{r}
plot_data$name <- factor(plot_data$name, levels=rev(order), ordered = TRUE)
p <- plot_data %>%
  filter(name !="All other drug combinations") %>% 
  ggplot(aes(x = growth, y = name)) +
  geom_segment(aes(
    y = name,
    x = 0,
    yend = name,
    xend = growth
  ),
  color = "black") +
  geom_point(stat = "identity", size = 2) +
  coord_cartesian(xlim = c(-10000, 20000)) +
  labs(
    # title = "Percentage change in Number of Overdose Deaths from 2011 to 2019, by Drugs Present",
    x = "Change in overdose deaths (people)",
    y = NULL,
    color = NULL
    # caption = "Data: National Center for Health Statistics, Centers for Disease Control and Prevention"
  ) +
  #scale_x_continuous(labels = percent_format(big.mark = ",")) +
  scale_x_continuous(labels = comma) +
  theme_bw() +
  theme(
    # plot.caption = element_text(hjust = 0, face = "italic"),
    # plot.title.position = "plot",
    # plot.caption.position =  "plot",
    panel.background = element_rect(fill = "#fcfbfa"),
    axis.text = element_text(color = "black")
  )
p

#ggsave("change_figure_ppl.png", dpi = "retina")
```

